server:
  port: 8401
  feign:
    okhttp:
      enabled: true # 开启OKHttp连接池⽀持

spring:
  security:
    user:
      name: root
      password: 123456
  boot:
    admin:
      ui:
        title: 微服务状态监控
